name: Cambridge University India Society
author: Anik Roy
email: anik545@gmail.com

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', vendor]

favicon: img/favicon.png

# links
facebook: https://www.facebook.com/indiasoc
facebook_events: https://www.facebook.com/pg/indiasoc/events
instagram: https://www.instagram.com/cuindiasoc/?hl=en
indiasoc_email: mailto:india@cusu.cam.ac.uk
mailing_list: https://lists.cam.ac.uk/mailman/listinfo/soc-indiasoc

pres_email: india@cusu.cam.ac.uk
treasurer_email: india@cusu.cam.ac.uk
ents_email: india@cusu.cam.ac.uk
sponsorship_email: india@cusu.cam.ac.uk

no_events: 6


collections:
  - events
