backend:
  name: git-gateway


media_folder: "img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Home Page'
        name: 'index'
        file: 'index.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Layout', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Body', name: 'body', widget: 'markdown' }